### ISSUE TITLE
[task] Modernize Lateralus

### ISSUE THREAD

**Issue by jeremyckahn** [Jellyvision/lateralus#27]
Lateralus is built on fairly outdated tech and needs to be modernized.

## Subtasks

- [x] Replace Grunt tasks with npm scripts
- [x] Convert all files from being AMD modules to ES6
- [x] Drop PhantomJS dependency for running unit tests
- [x] Replace RequireJS build process with Webpack/Babel
- [x] Drop Bower for pure NPM
- [x] Convert from leading comma to trailing
- [x] Switch from YUIDoc to [JSDoc](https://github.com/jsdoc3/jsdoc)
- [x] Untrack `dist`, but publish the build artifacts to npm

As a result of these changes, and given the stability of this project, satisfying this ticket warrants a 1.0.0 release.
